name: intelligence
description: "Apple's AppIntent integration plugin. Let your app be understood by Siri, the Shortcuts app, Apple Intelligence, and more."
version: 0.2.0
repository: https://github.com/monterail/intelligence
screenshots:
  - description: 'Example App Intent built with this plugin used in the Shortcuts workflow.'
    path: doc/assets/recipe1/draw_intent.jpg
topics:
  - ai
  - os-integration

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  montelints: ^1.0.0+2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IntelligencePlugin
